/**
 * AUTO-GENERATED by scripts/gen-service-contract.ts
 * Do not edit manually. Run `npm run gen:service-contract` to regenerate.
 */

import type { ISearchQueryService } from './search-query.js';
import type { ITagService } from './tag.js';
import type { ICafeService } from './cafe.js';
import type { IStationService } from './station.js';
import type { IUserService } from './user.js';
import type { IStationThemeService } from './station-theme.js';
import type { ISessionService } from './session.js';
import type { IReviewService } from './review.js';
import type { IGroupsService } from './groups.js';
import type { IMenuItemService } from './menu-item.js';
import type { IDailyMenuService } from './daily-menu.js';
import type { ISearchService } from './search.js';
import type { IMenuAnalyticsService } from './menu-analytics.js';
import type { ICartService } from './cart.js';
import type { IOrderService } from './order.js';

export interface DataServiceMap {
    searchQuery: ISearchQueryService;
    tag: ITagService;
    cafe: ICafeService;
    station: IStationService;
    user: IUserService;
    stationTheme: IStationThemeService;
    session: ISessionService;
    review: IReviewService;
    groups: IGroupsService;
    menuItem: IMenuItemService;
    dailyMenu: IDailyMenuService;
    search: ISearchService;
    menuAnalytics: IMenuAnalyticsService;
    cart: ICartService;
    order: IOrderService;
}

export const DATA_SERVICE_KEYS = {
    searchQuery: ['incrementSearchCount', 'getTopSearchQueries'] as const,
    tag: ['retrieveTags', 'createTags'] as const,
    cafe: ['retrieveCafe', 'retrieveCafes', 'doesCafeExist', 'createCafe', 'resetCache'] as const,
    station: ['createStation', 'retrieveStation', 'retrieveAllStationsWithoutGroup', 'retrieveAllStationNames'] as const,
    user: ['createUser', 'getUser', 'updateUserDisplayName', 'updateUserSettings'] as const,
    stationTheme: ['retrieveTheme'] as const,
    session: ['get', 'set', 'destroy'] as const,
    review: ['createMenuItemReview', 'createStationReview', 'getReviewsForMenuItem', 'getReviewsForStation', 'getReviewsForUser', 'retrieveReviewHeader', 'retrieveStationReviewHeader', 'retrieveReviewHeaderByParts', 'retrieveStationReviewHeaderByParts', 'getReviewById', 'getRecentReviews', 'updateReview', 'deleteReview', 'isOwnedByUser', 'getAllMenuItemReviewHeaders', 'getAllMenuItemReviewHeadersByGroupId', 'getMenuItemReviewHeaderByName', 'getReviewHeaderByGroupId', 'getAllStationReviewHeaders', 'getAllStationReviewHeadersByGroupId', 'getStationReviewHeaderByName', 'getStationReviewHeaderByGroupId'] as const,
    groups: ['getGroups', 'getGroupCandidatesZeroContext', 'getCandidatesForGroup', 'getGroupMembers', 'createGroup', 'updateGroup', 'deleteGroup', 'addToGroup', 'deleteMembersFromGroup'] as const,
    menuItem: ['saveMenuItem', 'saveMenuItemSearchTags', 'retrieveMenuItem', 'retrieveFirstMenuItemAppearance', 'retrieveMenuItemsForWeeklyMenu', 'retrievePendingSearchTagQueueEntries', 'getExistingSearchTagsForName', 'retrieveAllMenuItemsWithoutGroup', 'updateThumbnailHash', 'getCachedMenuItemNames', 'getTopSearchTags'] as const,
    dailyMenu: ['publishDailyStationMenuAsync', 'retrieveDailyMenuAsync', 'retrieveDailyCafeMenu', 'getMenuWatermark', 'retrieveDailyMenuOverviewHeadersAsync', 'isAnyMenuAvailableForDayAsync', 'getCafesAvailableForDayAsync', 'isAnyAllowedMenuAvailableForCafe', 'getPendingMenusForEmbedding', 'getMenusForSearch', 'retrieveCafeChildAvailability', 'retrieveStationItemAvailability', 'retrieveEntityVisits', 'retrieveFirstStationVisitsForCafe', 'retrieveFirstStationVisitDate', 'retrieveFirstMenuItemVisitDate', 'retrieveAllFirstMenuItemAppearances', 'getCafeHoursForDate', 'getStationHoursForDate', 'getAllCafeHoursForDate', 'upsertDailyCafeAsync', 'getShutDownCafesAsync', 'retrieveDailyCafeStateAsync'] as const,
    search: ['search', 'searchVector', 'searchForSimilarEntities', 'searchFavorites', 'searchForCheapItems', 'autocomplete', 'getSimilarQueries', 'getRecommendations'] as const,
    menuAnalytics: ['retrieveUniquenessDataForCafe', 'resolveIngredientsMenu', 'getShutdownCafeState', 'retrieveVisitData'] as const,
    cart: ['getCart', 'addItems', 'updateItem', 'removeItem', 'clearCart'] as const,
    order: ['preparePayment', 'completeOrder', 'getRecentOrders', 'getCompletedOrdersToday', 'getOrderHistory', 'getOrderCount'] as const,
} as const satisfies { [K in keyof DataServiceMap]: ReadonlyArray<keyof DataServiceMap[K]> };
