export interface IConnectorStop {
    id: string;
    name: string;
    address: string;
    city: string;
    hasParking: boolean;
    description: string;
    lat: number;
    lng: number;
    route: string;
    area: string;
}

export const CONNECTOR_STOPS: IConnectorStop[] = [
    {
        "id": "14c29b7e-c5f1-4ced-a842-5fdce20ca063",
        "name": "10th Ave E & E Aloha St",
        "address": "10th Ave E & E Aloha St",
        "city": "",
        "hasParking": false,
        "description": "On southbound 10th Ave E at the 3-minute load zone, just south of E Aloha St.\n\nRoute: North Capitol Hill AM & PM",
        "lat": 47.626564,
        "lng": -122.320359,
        "route": "North Capitol Hill AM & PM",
        "area": "Capitol Hill"
    },
    {
        "id": "d2d813e5-b0f0-46f0-8ca0-68501b480d0e",
        "name": "10th Ave NE & NE Falls Dr",
        "address": "10th Ave NE & NE Falls Dr",
        "city": "",
        "hasParking": false,
        "description": "Located on northbound 10th Ave NE at the SE corner near the crosswalk, just south of NE Falls Dr.\n \nRoute: Snoqualmie-issaquah AM & PM",
        "lat": 47.541574,
        "lng": -122.015916,
        "route": "Snoqualmie-Issaquah AM & PM",
        "area": "Snoqualmie & Issaquah"
    },
    {
        "id": "6debfd9f-568c-42b1-8876-79dbebffccf5",
        "name": "1101 Dexter Ave N",
        "address": "1101 Dexter Ave N",
        "city": "",
        "hasParking": false,
        "description": "At 30-min load zone near garage on southbound Dexter Ave N, in front of a major social media company office. \n\nRoute: South Lake Union AM & PM",
        "lat": 47.628739,
        "lng": -122.342447,
        "route": "South Lake Union AM & PM",
        "area": "South Lake Union"
    },
    {
        "id": "6b9b4efb-5d11-4b02-9e84-103f60a6e3e5",
        "name": "12th Ave E & E Pike St",
        "address": "12th Ave E & E Pike St",
        "city": "",
        "hasParking": false,
        "description": "Future stop: In the 5-min load zone on southbound 12th Ave E, south of Pike. See aka.ms/CommuteUpdates for details\n\nFuture route: Central Capitol Hill AM & PM",
        "lat": 47.61372966343506,
        "lng": -122.31697438510813,
        "route": "Central Capitol Hill AM & PM",
        "area": "Capitol Hill"
    },
    {
        "id": "7b40c20c-eb08-4fee-b5a3-80a3b11dc0f4",
        "name": "19th Ave E & E Harrison St",
        "address": "19th Ave E & E Harrison St",
        "city": "",
        "hasParking": false,
        "description": "On southbound 19th Ave E, south of East Harrison St. Shuttle Bus Zone next to Metro stop, in front of Kingdom Hall. \n\nRoute: Capitol Hill AM & PM",
        "lat": 47.621776,
        "lng": -122.307431,
        "route": "Capitol Hill AM & PM",
        "area": "Capitol Hill"
    },
    {
        "id": "11d611d8-34b3-4acc-b85e-666e567586aa",
        "name": "1st Ave & Cedar St (PM)",
        "address": "1st Ave & Cedar St (PM)",
        "city": "",
        "hasParking": false,
        "description": "Northbound midblock, at the Shuttle Bus sign. \n\nRoute: Queen Anne-belltown PM",
        "lat": 47.616059,
        "lng": -122.350956,
        "route": "Queen Anne-Belltown PM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "4dd474c1-7c0d-430b-9a7a-5afe9d602d2e",
        "name": "1st Ave N & Thomas St (Lenny Wilkins Way) (PM)",
        "address": "1st Ave N & Thomas St (Lenny Wilkins Way) (PM)",
        "city": "",
        "hasParking": false,
        "description": "On the east side of northbound 1st Ave N, just south of Thomas Street (Lenny Wilkens Way), in the loading zone.\n\nRoute: Queen Anne-belltown PM",
        "lat": 47.62076842,
        "lng": -122.35536051,
        "route": "Queen Anne-Belltown PM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "bbc9dbd1-819c-4b69-b4b2-d66a59b86e2c",
        "name": "23rd Ave & E Pine St (PM)",
        "address": "23rd Ave & E Pine St (PM)",
        "city": "",
        "hasParking": false,
        "description": "On southbound 23rd Ave just south of E Pine St at the shared Metro stop. \n\nRoute: Leschi-madrona-madison Park PM",
        "lat": 47.61514607,
        "lng": -122.30276934,
        "route": "Leschi-Madrona-Madison Park PM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "9e0a2baf-5bc5-49a0-96c7-b9bfed8884eb",
        "name": "24th Ave NW & NW 67th St",
        "address": "24th Ave NW & NW 67th St",
        "city": "",
        "hasParking": false,
        "description": "Northbound 3-minute load zone, south of NW 67th St (next to meditation center). \n\nRoute: Ballard-whittier Heights AM & PM",
        "lat": 47.677562,
        "lng": -122.387431,
        "route": "Ballard-Whittier Heights AM & PM",
        "area": "Ballard & Whittier Heights"
    },
    {
        "id": "a0c49c8e-3c0e-49bf-9d76-d5e7e6a34bfe",
        "name": "24th Ave NW & NW 77th St",
        "address": "24th Ave NW & NW 77th St",
        "city": "",
        "hasParking": false,
        "description": "Northbound 24th Ave NW in the 3-minute load zone, north of NW 77th St. and next to Philadelphia Church. \n\nRoute: Ballard-whittier Heights AM & PM",
        "lat": 47.685183,
        "lng": -122.387489,
        "route": "Ballard-Whittier Heights AM & PM",
        "area": "Ballard & Whittier Heights"
    },
    {
        "id": "49103887-9ccd-4372-8c5c-2657f1db8d7e",
        "name": "2nd Ave & Cedar St (AM)",
        "address": "2nd Ave & Cedar St (AM)",
        "city": "",
        "hasParking": false,
        "description": "Southbound on 2nd Ave, just north of Cedar St. At Shuttle stop only sign. \n\nRoute: Queen Ann-belltown AM",
        "lat": 47.616523,
        "lng": -122.350028,
        "route": "Queen Ann-Belltown AM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "9c537a63-88b9-497e-ab8d-283a2ceff72f",
        "name": "35th Ave NE & NE 73rd St",
        "address": "35th Ave NE & NE 73rd St",
        "city": "",
        "hasParking": false,
        "description": "In the 3-minute loading zone on northbound 35th Ave NE, in front of Messiah Lutheran Church. \n\nRoute: Laurelhurst-wedgwood AM & PM",
        "lat": 47.680796,
        "lng": -122.290341,
        "route": "Laurelhurst-Wedgwood AM & PM",
        "area": "Laurelhurst & Wedgwood"
    },
    {
        "id": "1fa6c9c2-ac35-4b2c-b6c1-19cec092e831",
        "name": "35th Ave NE & NE 80th St",
        "address": "35th Ave NE & NE 80th St",
        "city": "",
        "hasParking": false,
        "description": "Northbound 35th Ave NE, just south of NE 80th St. in the 3-minute load zone \n\nRoute: Laurelhurst-wedgwood AM & PM",
        "lat": 47.686476,
        "lng": -122.290508,
        "route": "Laurelhurst-Wedgwood AM & PM",
        "area": "Laurelhurst & Wedgwood"
    },
    {
        "id": "9af128c8-49d5-438a-842e-91ef8bdc5af8",
        "name": "3rd Ave NE & NE 141st Pl (AM)",
        "address": "3rd Ave NE & NE 141st Pl (AM)",
        "city": "",
        "hasParking": false,
        "description": "On 3rd Ave NE, north of NE 141st Pl, across the street from the stairs on the west side of the street. No parking is provided at this location. If parking is required, please use Holy Innocents Catholic Church\n\nRoute: Snohomish-monroe-duvall AM",
        "lat": 47.72885991,
        "lng": -121.98031059,
        "route": "Snohomish-Monroe-Duvall AM",
        "area": "Snohomish, Monroe & Duvall"
    },
    {
        "id": "b0c54993-d1ea-4a21-8893-781e218a2b27",
        "name": "3rd Ave NE & NE 141st Pl (PM)",
        "address": "3rd Ave NE & NE 141st Pl (PM)",
        "city": "",
        "hasParking": false,
        "description": "On 3rd Ave NE, north of NE 141st Pl, adjacent to the stairs. No parking is provided at this location. If parking is required, please use Holy Innocents Catholic Church\n\nRoute: Snohomish-monroe-duvall PM",
        "lat": 47.72886119,
        "lng": -121.98012851,
        "route": "Snohomish-Monroe-Duvall PM",
        "area": "Snohomish, Monroe & Duvall"
    },
    {
        "id": "392a586e-3619-487d-9abc-9505c6e1837b",
        "name": "40th Ave NE & NE 55th St",
        "address": "40th Ave NE & NE 55th St",
        "city": "",
        "hasParking": false,
        "description": "In the 3-min load zone on northbound 40th Ave NE, just north of the Burke-Gilman Trail. \n\nRoute: Laurelhurst-wedgwood AM & PM",
        "lat": 47.667613,
        "lng": -122.284749,
        "route": "Laurelhurst-Wedgwood AM & PM",
        "area": "Laurelhurst & Wedgwood"
    },
    {
        "id": "3af9e63d-3633-4a60-9162-93f932c257e9",
        "name": "6th Ave & Lenora St",
        "address": "6th Ave & Lenora St",
        "city": "",
        "hasParking": false,
        "description": "On northbound 6th Ave at the 15-minute Shuttle Bus Only sign, about mid-block between Lenora St. and Virginia St. \n\nRoute: South Lake Union AM & PM",
        "lat": 47.614923,
        "lng": -122.339028,
        "route": "South Lake Union AM & PM",
        "area": "South Lake Union"
    },
    {
        "id": "3d7c41bc-5bfd-44b6-b679-b4f79237a739",
        "name": "9 W Mcgraw St",
        "address": "9 W Mcgraw St",
        "city": "",
        "hasParking": false,
        "description": "On eastbound W McGraw St, west of Queen Anne Ave N. At the Shuttle Stop Only sign. \n\nRoute: Queen Anne-belltown AM",
        "lat": 47.639543,
        "lng": -122.357411,
        "route": "Queen Anne-Belltown AM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "dd96aef3-9881-4f22-af3e-780c464da06e",
        "name": "Bellevue Ave & E Pike St",
        "address": "Bellevue Ave & E Pike St",
        "city": "",
        "hasParking": false,
        "description": "Northbound on Bellevue Ave, just north of E Pike St. On west side of First Covenant Church. In the 3-minute load zone\n\nRoute: Capitol Hill AM & PM",
        "lat": 47.614293,
        "lng": -122.326733,
        "route": "Capitol Hill AM & PM",
        "area": "Capitol Hill"
    },
    {
        "id": "df1bf65c-e976-439a-aae2-76b893a12116",
        "name": "Boren Ave N & Harrison St (AM)",
        "address": "Boren Ave N & Harrison St (AM)",
        "city": "",
        "hasParking": false,
        "description": "At the 15-min Shuttle Bus Only sign, on southbound Boren Ave N, just south of Harrison St.\n\nRoute: South Lake Union AM",
        "lat": 47.62181,
        "lng": -122.335938,
        "route": "South Lake Union AM",
        "area": "South Lake Union"
    },
    {
        "id": "426179b7-8597-48fe-b087-b4b18a41e849",
        "name": "Bothell North Creek Plaza",
        "address": "Bothell North Creek Plaza",
        "city": "",
        "hasParking": true,
        "description": "Stop is mid-row in the far east lane of the parking lot at North Creek Plaza shopping center. Near 18438 120th Ave NE. \n\nParking is on the east side of the lot, 52 total stalls on either side of the Connector stop, 10 stalls to the south of the stop, and 35 stalls near the EV charging stations on the west side of the lot.\n\nRoute: Bothell AM & PM",
        "lat": 47.760565,
        "lng": -122.174769,
        "route": "Bothell AM & PM",
        "area": "Bothell"
    },
    {
        "id": "abb483c6-06eb-41cd-96ff-e141077ee1a5",
        "name": "California Ave SW @ Admiral Theater",
        "address": "California Ave SW @ Admiral Theater",
        "city": "",
        "hasParking": false,
        "description": "Southbound on California Ave SW, 3-min load zone next to Admiral Theater. No parking at theater.\n\nRoute: West Seattle AM & PM",
        "lat": 47.581739,
        "lng": -122.386599,
        "route": "West Seattle AM & PM",
        "area": "West Seattle"
    },
    {
        "id": "886664cf-49a3-43f5-9735-b876a0c38b88",
        "name": "California Ave SW & SW Spokane St",
        "address": "California Ave SW & SW Spokane St",
        "city": "",
        "hasParking": false,
        "description": "Southbound on California Ave SW south of SW Spokane St, next to church. Shared Metro stop.\n\nRoute: West Seattle AM & PM",
        "lat": 47.571855,
        "lng": -122.386888,
        "route": "West Seattle AM & PM",
        "area": "West Seattle"
    },
    {
        "id": "e110b1dc-db3c-48ef-829d-d5a3535ece10",
        "name": "Calvary Chapel of Lake Stevens",
        "address": "Calvary Chapel of Lake Stevens",
        "city": "",
        "hasParking": true,
        "description": "Future stop: Stop will be on the west side of the lot south of the church building. Parking will be 20 stalls to the south of the Connector stop. See map at aka.ms/CommuteUpdates",
        "lat": 47.991349,
        "lng": -122.103978,
        "route": "",
        "area": "Other"
    },
    {
        "id": "f45d5664-ae4d-4f55-b278-b58228f98c88",
        "name": "Cedar Park Crescent NE & NE 100th Way",
        "address": "Cedar Park Crescent NE & NE 100th Way",
        "city": "",
        "hasParking": false,
        "description": "On southbound NE Cedar Park Crescent, just south of NE 100th Way\n\nRoute: Redmond Ridge AM & PM",
        "lat": 47.687927,
        "lng": -122.041669,
        "route": "Redmond Ridge AM & PM",
        "area": "Redmond Ridge"
    },
    {
        "id": "ff31b081-34b6-4d60-aedf-bdefd51fb6e2",
        "name": "Cedar Park Crescent NE & Redmond Ridge Dr NE",
        "address": "Cedar Park Crescent NE & Redmond Ridge Dr NE",
        "city": "",
        "hasParking": true,
        "description": "On eastbound Cedar Park Crescent NE, just west of Redmond Ridge Dr NE. Public P&R parking, not reserved for Microsoft.\n\nRoute: Redmond Ridge AM & PM",
        "lat": 47.685752,
        "lng": -122.033588,
        "route": "Redmond Ridge AM & PM",
        "area": "Redmond Ridge"
    },
    {
        "id": "9c2e2dd0-4e85-4c32-8871-f5988de762be",
        "name": "Christian Faith Center",
        "address": "Christian Faith Center",
        "city": "",
        "hasParking": true,
        "description": "Stop is southbound on 21st Dr SE, near Connector sign. Parking hangtag required. Parking is in 39 stalls the lot in front of the main building, in the four rows closest to the street. Microsoft also has 11 stalls just south of the aisle, in the two rows closest to the street.\n\nRoute: S Everett-mill Creek AM & PM",
        "lat": 47.879043,
        "lng": -122.203597,
        "route": "S Everett-Mill Creek AM & PM",
        "area": "Mill Creek & Everett"
    },
    {
        "id": "6e7e7296-cdcf-4f8b-b29d-13a4c03478ff",
        "name": "Covington Cornerstone Church",
        "address": "Covington Cornerstone Church",
        "city": "",
        "hasParking": true,
        "description": "East side of church outer lot, close to 209th Ave NE. Street address is 20730 SE 272nd St. Parking is in 25 stalls on the east side of the lot in the middle two rows.\n\nRoute: Maple Valley-kent AM & PM",
        "lat": 47.358488,
        "lng": -122.063518,
        "route": "Maple Valley-Kent AM & PM",
        "area": "Maple Valley & Kent"
    },
    {
        "id": "819c3b0f-cb6d-472c-8159-2961a4e532a7",
        "name": "E Cherry St & 16th Ave (AM)",
        "address": "E Cherry St & 16th Ave (AM)",
        "city": "",
        "hasParking": false,
        "description": "On eastbound E Cherry St, east of 16th Ave, in the 3-minute load zone next to the hospital. \n\nRoute: Leschi-madrona-madison Park AM",
        "lat": 47.607983,
        "lng": -122.311412,
        "route": "Leschi-Madrona-Madison Park AM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "42ca83d2-ed1d-4e2e-b806-51877757b454",
        "name": "E Cherry St & 18th Ave (PM)",
        "address": "E Cherry St & 18th Ave (PM)",
        "city": "",
        "hasParking": false,
        "description": "On the northwest side of the intersection.  In the 3-min Passenger Load Zone.\n\nRoute: Leschi-madrona-madison Park PM",
        "lat": 47.608074,
        "lng": -122.309199,
        "route": "Leschi-Madrona-Madison Park PM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "07076758-b8a0-4fba-9e26-2f8f785e9640",
        "name": "E Madison St & 23rd Ave E (AM)",
        "address": "E Madison St & 23rd Ave E (AM)",
        "city": "",
        "hasParking": false,
        "description": "Northbound Madison, 30-min load zone northeast of 23rd Ave E, past the Metro stop. \n\nRoute: Leschi-madrona-madison Park AM",
        "lat": 47.619336,
        "lng": -122.302192,
        "route": "Leschi-Madrona-Madison Park AM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "914aab30-2f0d-405d-9598-937f81011d7c",
        "name": "E Madison St & 28th Ave E (AM)",
        "address": "E Madison St & 28th Ave E (AM)",
        "city": "",
        "hasParking": false,
        "description": "On eastbound E Madison St, east of 28th Ave E, and west of 29th Ave E. in the 30-minute loading zone. \n\nRoute: Leschi-madrona-madison Park AM",
        "lat": 47.62357549,
        "lng": -122.2958871,
        "route": "Leschi-Madrona-Madison Park AM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "1bb588f6-05dc-42cf-bf11-a56f17a8730f",
        "name": "E Olive Way & Harvard Ave E",
        "address": "E Olive Way & Harvard Ave E",
        "city": "",
        "hasParking": false,
        "description": "In the 3-minute load zone on westbound E Olive Way, just east of Harvard Ave\n\nRoute: North Capitol Hill",
        "lat": 47.619979,
        "lng": -122.321984,
        "route": "North Capitol Hill",
        "area": "Capitol Hill"
    },
    {
        "id": "e5dc9c0d-75bc-42b0-9d4e-cc3d7c2b59f3",
        "name": "E Union St & 33rd Ave (PM)",
        "address": "E Union St & 33rd Ave (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. On eastbound E Union St, west of 33rd Ave. In the 3-minute Passenger Load Zone. \n\nRoute: Leschi-madrona-madison Park PM",
        "lat": 47.612864,
        "lng": -122.290481,
        "route": "Leschi-Madrona-Madison Park PM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "75c38c73-c360-4a7d-8c12-b3c5f2aae55a",
        "name": "E Union St & 34th Ave (AM)",
        "address": "E Union St & 34th Ave (AM)",
        "city": "",
        "hasParking": false,
        "description": "At the 3-min load zone on westbound E Union St, just west of 34th Ave. \n\nRoute: Leschi-madrona-madison Park AM",
        "lat": 47.612948,
        "lng": -122.289651,
        "route": "Leschi-Madrona-Madison Park AM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "bc552ca1-ad98-4467-9134-bbfded39cfcf",
        "name": "Eastridge Dr NE & Powerlines",
        "address": "Eastridge Dr NE & Powerlines",
        "city": "",
        "hasParking": false,
        "description": "On northbound Eastridge Dr NE, between the trail crossing and NE 110th St, across from the southbound Metro stop.\n\nRoute: Redmond Ridge AM & PM",
        "lat": 47.69713468,
        "lng": -122.0188483,
        "route": "Redmond Ridge AM & PM",
        "area": "Redmond Ridge"
    },
    {
        "id": "43e830b6-89a5-4ebb-a287-e70fdf17e995",
        "name": "Evergreen State Fairgrounds",
        "address": "Evergreen State Fairgrounds",
        "city": "",
        "hasParking": true,
        "description": "Stop is in the middle driveway of the main parking lot, east of 179th Ave NE. \n\nParking is 25 stalls in the main parking lot, north of the divider aisle.\n\nRoute: Snohomish-monroe-duvall AM & PM",
        "lat": 47.867032,
        "lng": -121.990045,
        "route": "Snohomish-Monroe-Duvall AM & PM",
        "area": "Snohomish, Monroe & Duvall"
    },
    {
        "id": "e88a3f39-82e2-4012-beba-ef3e44cdef12",
        "name": "Genesee Park (Parking Lot)",
        "address": "Genesee Park (Parking Lot)",
        "city": "",
        "hasParking": false,
        "description": "North end of lot before exiting, south of S. Genessee St. Parking is NOT provided. \n\nRoute: Columbia City AM & PM",
        "lat": 47.56346252,
        "lng": -122.2795605,
        "route": "Columbia City AM & PM",
        "area": "Columbia City"
    },
    {
        "id": "12113dd4-f2d8-4e90-82fa-b58703c07c35",
        "name": "Greenwood Ave N & N 71st St (PM)",
        "address": "Greenwood Ave N & N 71st St (PM)",
        "city": "",
        "hasParking": false,
        "description": "On northbound Greenwood Ave N, north of N 71st St. In front of the Greentree building.  In the 30-minute load zone\n\nRoute: Phinney Ridge-green Lake PM",
        "lat": 47.68055495,
        "lng": -122.35520964,
        "route": "Phinney Ridge-Green Lake PM",
        "area": "Phinney Ridge & Green Lake"
    },
    {
        "id": "a5c7c2f2-ada0-42ab-97b3-a187366740a0",
        "name": "Greenwood Ave N & N 73rd St (AM)",
        "address": "Greenwood Ave N & N 73rd St (AM)",
        "city": "",
        "hasParking": false,
        "description": "Southbound on Greenwood Ave N, at the 30-minute load zone, north of N 73rd St.\n\nRoute: Phinney Ridge-green Lake AM",
        "lat": 47.681925,
        "lng": -122.355359,
        "route": "Phinney Ridge-Green Lake AM",
        "area": "Phinney Ridge & Green Lake"
    },
    {
        "id": "0694c071-d16c-4335-84b6-7ace36e62c93",
        "name": "Highlands Community Church",
        "address": "Highlands Community Church",
        "city": "",
        "hasParking": true,
        "description": "Stop is in the middle row of the parking lot between the church and NE 9th St. Street address is 3031 NE 10th St. \n\nParking is in 32 stalls to the west of the church building in the main lot, north of NE 9th St.\n\nRoute: Renton AM & PM",
        "lat": 47.497689,
        "lng": -122.178781,
        "route": "Renton AM & PM",
        "area": "Renton"
    },
    {
        "id": "cc551aed-0a7f-42a1-8d6e-b63fbf2b6c4d",
        "name": "Holy Innocents Catholic Church",
        "address": "Holy Innocents Catholic Church",
        "city": "",
        "hasParking": true,
        "description": "Stop is in the lower lot on the northwest side of the building, north of NE Cherry Valley Rd. Near 26526 NE Cherry Valley Rd. Parking is in 15 stalls in two rows at the north end of the lot.\n\nRoute: Snohomish-monroe-duvall AM & PM",
        "lat": 47.748673,
        "lng": -121.982256,
        "route": "Snohomish-Monroe-Duvall AM & PM",
        "area": "Snohomish, Monroe & Duvall"
    },
    {
        "id": "8fcf3dd0-6de6-49dc-8333-37d41b091994",
        "name": "Kent Seventh Day Adventist Church",
        "address": "Kent Seventh Day Adventist Church",
        "city": "",
        "hasParking": true,
        "description": "Stop is on the west side of the parking lot behind the church. Street address is 25213 116th AVE SE. Parking is in 35 stalls in the south portion of the lot and in the south middle aisles west of the church.\n\nRoute: Maple Valley Kent AM & PM",
        "lat": 47.375542,
        "lng": -122.188277,
        "route": "Maple Valley Kent AM & PM",
        "area": "Maple Valley & Kent"
    },
    {
        "id": "b85ff5a9-b36a-4a88-865e-133a1ed02b5d",
        "name": "Lake Washington Blvd E & E Madison St (PM)",
        "address": "Lake Washington Blvd E & E Madison St (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. On westbound E Madison St west of the Metro stop, in the Passenger Load Zone\n\nRoute: Leschi-madrona-madison Park PM",
        "lat": 47.625829,
        "lng": -122.292833,
        "route": "Leschi-Madrona-Madison Park PM",
        "area": "Leschi, Madrona & Madison Park"
    },
    {
        "id": "28810080-3af0-431b-b9ea-8560deb1a8a3",
        "name": "Mill Creek Foursquare Church",
        "address": "Mill Creek Foursquare Church",
        "city": "",
        "hasParking": true,
        "description": "Stop is northwest, mid lot. Street address is 1415 164th St. Parking hangtag required. Parking is west of the church building, north of the lawn and including to the northern border of the lot adjacent to Motor Place.\n\nRoutes: Mill Creek Express AM & PM, S. EVERETT MILL CREEK AM & PM",
        "lat": 47.850812,
        "lng": -122.253861,
        "route": "Mill Creek Express AM & PM, S. Everett Mill Creek AM & PM",
        "area": "Mill Creek & Everett"
    },
    {
        "id": "d4ab2369-c7cb-4ef8-baae-932d23a18b67",
        "name": "N 35th St & Woodland Park Ave N (AM)",
        "address": "N 35th St & Woodland Park Ave N (AM)",
        "city": "",
        "hasParking": false,
        "description": "At the 30-minute load zone on eastbound N 35th St, in front of the nursery.\n\nRoute: Fremont-wallingford AM",
        "lat": 47.649667,
        "lng": -122.344435,
        "route": "Fremont-Wallingford AM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "27063238-a698-4500-aca7-512bde6479ff",
        "name": "N 35th St & Woodland Park Ave N (PM)",
        "address": "N 35th St & Woodland Park Ave N (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. On westbound N 35th St, east of Woodland Park Ave N. \n\nRoute: Fremont-wallingford PM",
        "lat": 47.649677,
        "lng": -122.343885,
        "route": "Fremont-Wallingford PM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "52589973-0aa3-40ab-bf12-6511c0efb2c4",
        "name": "N 36th St & Francis Ave N",
        "address": "N 36th St & Francis Ave N",
        "city": "",
        "hasParking": false,
        "description": "On eastbound N 36th St, just west of Francis Ave N. East of the Metro stop near 417 N 36th St. \n\nRoute: Fremont-wallingford AM & PM",
        "lat": 47.65198644362647,
        "lng": -122.35376928069023,
        "route": "Fremont-Wallingford AM & PM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "069eb811-aa44-44a8-9273-e9a349d42c8d",
        "name": "N 45th St & Bagley Ave N (AM)",
        "address": "N 45th St & Bagley Ave N (AM)",
        "city": "",
        "hasParking": false,
        "description": "Eastbound on N 45th St, 3-min load zone, mid-block west of Bagley.\n\nRoute: Fremont-wallingford AM",
        "lat": 47.661322,
        "lng": -122.332879,
        "route": "Fremont-Wallingford AM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "259f5f9d-7b6a-4a94-bd17-e3925a701de0",
        "name": "N 45th St & Meridian Ave N (PM)",
        "address": "N 45th St & Meridian Ave N (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. Westbound N 45th St, west of Meridian Ave N. In the 5-minute load zone.\n\nRoute: Fremont Wallingford PM",
        "lat": 47.661444,
        "lng": -122.333948,
        "route": "Fremont Wallingford PM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "7caec5e7-b826-42aa-85e3-7d0f358246a4",
        "name": "N 65th St & Sunnyside Ave N (PM)",
        "address": "N 65th St & Sunnyside Ave N (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. Westbound on N 65th St, east of Sunnyside Ave N.  In the 3-minute load zone\n\nRoute: Phinney Ridge-green Lake PM",
        "lat": 47.676021,
        "lng": -122.329365,
        "route": "Phinney Ridge-Green Lake PM",
        "area": "Phinney Ridge & Green Lake"
    },
    {
        "id": "232422ba-75bb-4e0e-aac7-6528ebd46fc2",
        "name": "NE 65th St & 39th Ave NE",
        "address": "NE 65th St & 39th Ave NE",
        "city": "",
        "hasParking": false,
        "description": "On westbound NE 65th St, at the Shared Metro stop, east of 39th Ave NE.\n\nRoute: Laurelhurst-wedgwood AM & PM",
        "lat": 47.675855,
        "lng": -122.285785,
        "route": "Laurelhurst-Wedgwood AM & PM",
        "area": "Laurelhurst & Wedgwood"
    },
    {
        "id": "14ee70e9-04eb-44dd-8eba-5959ecb3b7ce",
        "name": "NE 65th St & Latona Ave NE (AM)",
        "address": "NE 65th St & Latona Ave NE (AM)",
        "city": "",
        "hasParking": false,
        "description": "Eastbound on NE 65th St, just west of Latona Ave NE. In the 3-minute load zone\n\nRoute: Phinney Ridge - Green Lake AM",
        "lat": 47.675859,
        "lng": -122.325631,
        "route": "Phinney Ridge - Green Lake AM",
        "area": "Phinney Ridge & Green Lake"
    },
    {
        "id": "da0b3512-c175-4585-a1a9-1c4cd0c6a7dd",
        "name": "NE Cedar Park Crescent & Eastridge Dr NE",
        "address": "NE Cedar Park Crescent & Eastridge Dr NE",
        "city": "",
        "hasParking": false,
        "description": "At the concrete pad on eastbound NE Cedar Park Crescent, near the basketball court.\n\nRoute: Redmond Ridge AM & PM",
        "lat": 47.691139,
        "lng": -122.017907,
        "route": "Redmond Ridge AM & PM",
        "area": "Redmond Ridge"
    },
    {
        "id": "cd9657c0-107d-48d8-a967-716a4d3f9ee4",
        "name": "NW Market St & 20th Ave NW",
        "address": "NW Market St & 20th Ave NW",
        "city": "",
        "hasParking": false,
        "description": "On westbound NW Market St, west of the Metro stop, in front of the Masonic center.  In the 3-minute load zone.\n\nRoute: Ballard-whittier Heights AM & PM",
        "lat": 47.668751,
        "lng": -122.382363,
        "route": "Ballard-Whittier Heights AM & PM",
        "area": "Ballard & Whittier Heights"
    },
    {
        "id": "2cd67380-2e8e-47a7-8542-45538db85a16",
        "name": "Our Redeemer's Lutheran Church",
        "address": "Our Redeemer's Lutheran Church",
        "city": "",
        "hasParking": true,
        "description": "Stop is in the parking lot behind the church, west of 25th Ave NW, near the P-Patch. Parking is in 35 stalls in the middle row. Counting southward from the P-Patch, Microsoft stalls are in rows 2, 3, and 4.\n\nRoute: Ballard-whittier Heights AM & PM",
        "lat": 47.691202,
        "lng": -122.389298,
        "route": "Ballard-Whittier Heights AM & PM",
        "area": "Ballard & Whittier Heights"
    },
    {
        "id": "9b44679f-6bab-4d83-b6d8-b28afaa3e79a",
        "name": "Phinney Ave N & N 55th St (PM)",
        "address": "Phinney Ave N & N 55th St (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. Northbound on Phinney Ave N, south of N 55th St.\n\nRoute: Phinney Ridge - Green Lake PM",
        "lat": 47.668305,
        "lng": -122.354312,
        "route": "Phinney Ridge - Green Lake PM",
        "area": "Phinney Ridge & Green Lake"
    },
    {
        "id": "38f3342f-6356-46db-bf95-9f1df7154c01",
        "name": "Phinney Ave N & N Argyle Pl (AM)",
        "address": "Phinney Ave N & N Argyle Pl (AM)",
        "city": "",
        "hasParking": false,
        "description": "On southbound Phinney Ave N, south of N Argyle Pl, next to St. John United Lutheran Church.\n\nRoute: Phinney Ridge-green Lake AM",
        "lat": 47.668971,
        "lng": -122.354504,
        "route": "Phinney Ridge-Green Lake AM",
        "area": "Phinney Ridge & Green Lake"
    },
    {
        "id": "968d926b-20c0-4de8-a2be-9f914576eb53",
        "name": "Queen Anne Ave N & Crockett St",
        "address": "Queen Anne Ave N & Crockett St",
        "city": "",
        "hasParking": false,
        "description": "PM only. Northbound on Queen Anne Ave N, north of Crockett St, in the Shuttle Bus Zone.\n\nRoute: Queen Anne-belltown PM",
        "lat": 47.637586,
        "lng": -122.356887,
        "route": "Queen Anne-Belltown PM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "ae1830ed-fbc7-46ec-8207-f5ebe32286d9",
        "name": "Queen Anne Ave N & W Comstock St",
        "address": "Queen Anne Ave N & W Comstock St",
        "city": "",
        "hasParking": false,
        "description": "Southtbound on Queen Anne Ave N, south of W Comstock St. At Shuttle Stop Only sign.\n\nRoute: Queen Anne-belltown AM & PM",
        "lat": 47.630359,
        "lng": -122.356696,
        "route": "Queen Anne-Belltown AM & PM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "c0760cb6-8439-43e7-a23f-ee1acb41041e",
        "name": "Queen Anne Ave N & W Harrison St (AM)",
        "address": "Queen Anne Ave N & W Harrison St (AM)",
        "city": "",
        "hasParking": false,
        "description": "On southbound Queen Anne Ave N, south of W Harrison St, just past the Metro stop\n\nRoute: Queen Anne-belltown AM",
        "lat": 47.62199,
        "lng": -122.356816,
        "route": "Queen Anne-Belltown AM",
        "area": "Queen Anne & Belltown"
    },
    {
        "id": "d59ffcdd-8725-4e4f-9929-b7165478b738",
        "name": "S Mcclellan & 34th Ave S (PM)",
        "address": "S Mcclellan & 34th Ave S (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. On eastbound S. McClellan St, west of 34th Ave S.\n\nRoute: Columbia City PM",
        "lat": 47.578291,
        "lng": -122.290122,
        "route": "Columbia City PM",
        "area": "Columbia City"
    },
    {
        "id": "c0086040-3bba-485b-978a-65cc445d9a5c",
        "name": "S Mcclellan St & S Mt Baker Blvd (AM)",
        "address": "S Mcclellan St & S Mt Baker Blvd (AM)",
        "city": "",
        "hasParking": false,
        "description": "Westbound on S McClellan St, east of S Mt. Baker Blvd, 3-minute load zone near Metro stop.\n\nRoute: Columbia City AM",
        "lat": 47.57842,
        "lng": -122.288907,
        "route": "Columbia City AM",
        "area": "Columbia City"
    },
    {
        "id": "ad402048-4239-4c3d-9a74-0d1fd33a5447",
        "name": "S Orcas St & 52nd Ave S",
        "address": "S Orcas St & 52nd Ave S",
        "city": "",
        "hasParking": true,
        "description": "In the 3-min load zone on westbound S McClellan St, east of S Mt. Baker Blvd, near the Metro stop.\n\nParking is in the church lot. Microsoft leases 20 stalls in the main lot.\n\nRoute: Columbia City AM & PM",
        "lat": 47.551206,
        "lng": -122.266754,
        "route": "Columbia City AM & PM",
        "area": "Columbia City"
    },
    {
        "id": "f86684ce-f76e-481f-a9c7-8f2939ac8a50",
        "name": "Sammamish Connector",
        "address": "Sammamish Connector",
        "city": "",
        "hasParking": true,
        "description": "In the parking lot just east of 228th Ave NE. Microsoft parking stalls are marked by signage and are closest to 228th Ave NE, as well as the diagonal row adjacent.\n\nFormerly called \"Central Washington University\". Name change is the only change.\n\nRoute: Sammamish Plateau AM & PM",
        "lat": 47.610943,
        "lng": -122.034962,
        "route": "Sammamish Plateau AM & PM",
        "area": "Sammamish"
    },
    {
        "id": "5c7034ec-0062-459d-b69f-b7c6c6286a6a",
        "name": "Snohomish Hope Foursquare Church",
        "address": "Snohomish Hope Foursquare Church",
        "city": "",
        "hasParking": true,
        "description": "Stop is in the west parking lot of the church, east of Bickford Ave.  Street address is 5002 Bickford Ave. \n\nParking is in 25 stalls on the west end of the lot.\n\nRoute: Snohomish-monroe-duvall AM & PM",
        "lat": 47.950342,
        "lng": -122.118019,
        "route": "Snohomish-Monroe-Duvall AM & PM",
        "area": "Snohomish, Monroe & Duvall"
    },
    {
        "id": "fce6a754-6694-4617-a492-7d26ca9631d9",
        "name": "St Elizabeth Church Bothell",
        "address": "St Elizabeth Church Bothell",
        "city": "",
        "hasParking": true,
        "description": "Boarding is in the south lane of the west parking lot at St Elizabeth Ann Seton Catholic Church. The lot is on the south side of 180th St SE.\n\nIMPORTANT: please only park in stalls stenciled #1-40. Parking is in the west lot, in the westernmost row of stalls and 13 stalls in southern end of the adjacent row. \n\nRoute: Bothell AM & PM",
        "lat": 47.833485,
        "lng": -122.200831,
        "route": "Bothell AM & PM",
        "area": "Bothell"
    },
    {
        "id": "b52f2892-1405-4a16-a5c1-bb8c17634f6c",
        "name": "Stone Way N & N 45th St (AM)",
        "address": "Stone Way N & N 45th St (AM)",
        "city": "",
        "hasParking": false,
        "description": "In the 3-minute load zone on northbound Stone Way N, south of N 45th St, near Wallingford Plaza.\n\nRoute: Fremont Wallingford AM",
        "lat": 47.660875,
        "lng": -122.342079,
        "route": "Fremont Wallingford AM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "51ff7224-74cd-4956-81bd-67f128357db6",
        "name": "Thomas St & 9th Ave N (PM)",
        "address": "Thomas St & 9th Ave N (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. Westbound on Thomas St, west of 9th Ave N.\n\nRoute: South Lake Union PM",
        "lat": 47.620896,
        "lng": -122.339531,
        "route": "South Lake Union PM",
        "area": "South Lake Union"
    },
    {
        "id": "40a2feda-7e2a-49dc-ab94-2503c98ce0ec",
        "name": "Trailside Building",
        "address": "Trailside Building",
        "city": "",
        "hasParking": true,
        "description": "Stop is northwest of the Church on the Ridge/preschool, on the southeast side of the Trailside Building parking lot. \n\nParking is in 20 stalls on the southwest edge of the lot behind 35131 SE Douglas St.\n\nRoute: Snoqualmie-issaquah AM & PM",
        "lat": 47.525064,
        "lng": -121.871316,
        "route": "Snoqualmie-Issaquah AM & PM",
        "area": "Snoqualmie & Issaquah"
    },
    {
        "id": "14c00ff7-1f10-4681-93a9-60d82db01e9f",
        "name": "Union Hill Parking (Temporary)",
        "address": "Union Hill Parking (Temporary)",
        "city": "",
        "hasParking": true,
        "description": "",
        "lat": 47.676251,
        "lng": -122.082381,
        "route": "",
        "area": "Other"
    },
    {
        "id": "375871e9-640e-42d8-bc1a-2c08ecd3cd1b",
        "name": "Uw Bicycle",
        "address": "Uw Bicycle",
        "city": "",
        "hasParking": false,
        "description": "Just east of UW Station, near the sign displaying \"Paratransit & Shuttles\" Route: Sr-520 Bicycle (Connector)",
        "lat": 47.6498,
        "lng": -122.3037,
        "route": "Sr-520 Bicycle (Connector)",
        "area": "Other"
    },
    {
        "id": "e067b048-9549-45c4-813e-52388596e837",
        "name": "W Seattle Christian Church",
        "address": "W Seattle Christian Church",
        "city": "",
        "hasParking": true,
        "description": "Parking hangtag required. Parking is in 50 stalls in the lot west of 41st Ave SW, near 4401 42nd Ave SW. Board on 41st Ave SW just south of SW Genesee St.\n\nRoute: West Seattle AM & PM",
        "lat": 47.56454,
        "lng": -122.384203,
        "route": "West Seattle AM & PM",
        "area": "West Seattle"
    },
    {
        "id": "ca245423-1da0-4625-b65e-51f60316a11d",
        "name": "Wallingford Ave N & N 34th St  (PM)",
        "address": "Wallingford Ave N & N 34th St  (PM)",
        "city": "",
        "hasParking": false,
        "description": "On southbound Wallingford Ave N, north of N 34th St. In the 30-minute load zone\n\nRoute: Fremont-wallingford PM",
        "lat": 47.648249,
        "lng": -122.336443,
        "route": "Fremont-Wallingford PM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "0bdf0935-ed15-4042-89fe-1e29af1d98af",
        "name": "Wallingford Ave N & N 34th St (AM)",
        "address": "Wallingford Ave N & N 34th St (AM)",
        "city": "",
        "hasParking": false,
        "description": "On southbound Wallingford Ave N, at the 30-min load zone just north of N 34th St.\n\nRoute: Fremont-wallingford AM",
        "lat": 47.648542,
        "lng": -122.336288,
        "route": "Fremont-Wallingford AM",
        "area": "Fremont & Wallingford"
    },
    {
        "id": "79c31167-b418-4a82-bbc9-1a90c471127b",
        "name": "Wallingford Ave N & N 43rd St (PM)",
        "address": "Wallingford Ave N & N 43rd St (PM)",
        "city": "",
        "hasParking": false,
        "description": "PM only. On southbound Wallingford Ave N, south of N 43rd St.  In the 3-minute load zone\n\nRoute: Fremont-wallingford PM",
        "lat": 47.658774,
        "lng": -122.336325,
        "route": "Fremont-Wallingford PM",
        "area": "Fremont & Wallingford"
    }
];
